<a href="https://colab.research.google.com/github/redwanulhaider13/numericals/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
array = np.random.rand(10,5)
print(array)

[[0.0772824  0.25431484 0.71984327 0.95105984 0.67824235]
 [0.28083286 0.93573384 0.84780112 0.83912133 0.03989275]
 [0.4813536  0.01125583 0.36366068 0.24707308 0.52005718]
 [0.6110158  0.56960758 0.0956872  0.2838997  0.44092549]
 [0.97033943 0.47365226 0.43134706 0.52133964 0.7027014 ]
 [0.25593618 0.5545642  0.18878989 0.0253406  0.84238727]
 [0.56320484 0.41241575 0.72390043 0.85245112 0.20652692]
 [0.33804861 0.16917323 0.66898069 0.60217428 0.14209362]
 [0.80407201 0.22178283 0.85604472 0.40546659 0.59050369]
 [0.17262116 0.16564925 0.64968746 0.40172002 0.51367287]]


In [11]:
#problem 1
sum = np.sum(array)
mean = np.mean(array)
print('sum is')
print(sum)
print('mean is')
print(mean)

sum is
23.675248711103656
mean is
0.4735049742220731


In [15]:
sum_thirdcolumn= np.mean(array[:,2])
print(sum_thirdcolumn)

0.5545742502693685


In [16]:
vector = [25,16,9,4,1]
squares= []
for x in vector:
  squares.append(x**2)
print(squares)

[625, 256, 81, 16, 1]


In [22]:
x=7
a = np.arange(1,x+1)
a[::-1].sort()
print(a)
squares= []
for x in a:
  squares.append(x**2)
print(squares)

[7 6 5 4 3 2 1]
[49, 36, 25, 16, 9, 4, 1]


In [26]:
b = np.array([[1,0,0,2,2],[0,1,0,2,2],[0,0,1,2,2],[25,16,9,4,1]])
print(b)

[[ 1  0  0  2  2]
 [ 0  1  0  2  2]
 [ 0  0  1  2  2]
 [25 16  9  4  1]]
